devices:
  samplerate: 48000
  chunksize: 1024
  capture:
    type: CoreAudio
    device: "BlackHole 2ch"
    channels: 2
  playback:
    type: CoreAudio
    device: 'USB Audio CODEC '
    channels: 2
pipeline:
- type: Filter
  channels:
  - 0
  - 1
  names:
  - gain_in
- type: Filter
  channels:
  - 0
  names:
  - fir_L
- type: Filter
  channels:
  - 1
  names:
  - fir_R
- type: Filter
  channels:
  - 0
  - 1
  names:
  - gain_out
filters:
  gain_in:
    type: Gain
    parameters:
      gain: 6.00
      scale: dB
      inverted: false
  gain_out:
    type: Gain
    parameters:
      gain: 1.53
      scale: dB
      inverted: false
  fir_L:
    type: Conv
    parameters:
      type: Wav
      filename: "/Users/jeremy/Coding/FIRC/FIRC_git/resources/impulse_L.wav"
      channel: 0
  fir_R:
    type: Conv
    parameters:
      type: Wav
      filename: "/Users/jeremy/Coding/FIRC/FIRC_git/resources/impulse_R.wav"
      channel: 0
